# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e14189a21e2d005cebefb0de8f3f3ba2bcabf96dcf4c78e318315d30af77fe1747aa03a0c2bd15b53a7df06af7d609c4c04fa2aa98302f8b1194d715951f75ce

test:
  secret_key_base: 5831dc822a2558ad951222a50bf310796fc83377d1b100201a76a484e09b07dfd6bd7b14ebbefeeb45a8a7913fd82c62634483ea050032a477448cefb8b2a1c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
